name: build new version

on:
  discussion:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        if: github.actor == 'zhangyu1818'
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
